--
-- PostgreSQL database dump
--

\restrict vSmYGYObsfO0QtWw6yiKWP13C4FGfwUTsLMej3hoH2hMLAj7vO9fmz2lF4PYH24

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: regulation; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (11, 'Wft', 'Wet op het financieel toezicht', 'National law', 'NL', 'Prudentieel/gedragstoezicht; operationele risico’s.', 'Van kracht', NULL, NULL, '[{"text": "Behoorlijke bedrijfsvoering"}, {"text": "Risicobeheer"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 42, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (10, 'Wwft', 'Wet ter voorkoming van witwassen en financieren van terrorisme', 'National law', 'NL', 'CDD/KYC, transactiemonitoring, meldplicht ongebruikelijke transacties.', 'Van kracht; intensief toezicht; hoge boetes mogelijk', NULL, NULL, '[{"text": "Cliëntenonderzoek"}, {"text": "Risicogebaseerde monitoring"}, {"text": "Tijdige meldingen aan FIU-NL"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 42, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (13, 'PSD2-SCA (RTS)', 'RTS on SCA & CSC', 'Regulatory Technical Standards', 'EU', 'Sterke klantauthenticatie; veilige communicatie.', 'Van kracht', NULL, NULL, '[{"text": "SCA-vereisten"}, {"text": "API-beveiliging"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 44, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (15, 'DORA', 'Digital Operational Resilience Act', 'Regulation', 'EU', 'ICT-risicobeheer, incidentmelding, testprogramma’s, third-party oversight.', 'Van kracht; implementatie richting 2025', NULL, NULL, '[{"text": "Incidentmelding binnen 4 uur en volledig binnen 1 maand"}, {"text": "Pen-tests"}, {"text": "Toezicht kritieke ICT-leveranciers"}]', '[{"text": "Toepassing: 2025-01-17"}]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 42, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (16, 'PAD', 'Payment Accounts Directive', 'Directive', 'EU', 'Transparantie betaalrekeningen; basis-betaalrekening.', 'Van kracht', NULL, NULL, '[{"text": "Vergelijkbaarheid kosten"}, {"text": "Basisrekening toegang"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 40, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (17, 'FiDA', 'Financial Data Access Regulation (proposal)', 'Regulation', 'EU', '“Open finance”: data-deling over producten zoals hypotheken, sparen, beleggen.', 'Voorstel; voorbereiding op inventarisatie en API-standaarden', NULL, NULL, '[{"text": "Toestemming-gebaseerde data-deling"}, {"text": "Vergoedingen"}, {"text": "Technische standaarden"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 40, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (6, 'BW Boek 7', 'Burgerlijk Wetboek Boek 7 (betalingsopdrachten)', 'National law', 'NL', 'Civielrechtelijke regels rond betaalopdrachten en aansprakelijkheid.', 'Van kracht', NULL, NULL, '[{"text": "Aansprakelijkheid"}, {"text": "Informatieplichten"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:09:05.178748+00', NULL, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (18, 'MiCA', 'Markets in Crypto-Assets', 'Regulation', 'EU', 'Geharmoniseerd regime voor crypto-dienstverleners.', 'Van kracht; banken/fintechs richten CASP-compliance in', NULL, NULL, '[{"text": "Autorisatie CASPs"}, {"text": "Reserves stablecoins"}, {"text": "Informatie- en gedragsregels"}, {"text": "Klachtenafhandeling"}]', '[{"text": "Volledig toepasbaar vanaf 2024-12-01"}]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 37, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (1, 'PSD2', 'Payment Services Directive 2', 'Directive', 'EU+NL', 'Regels voor betaaldiensten, open banking, toegang derde partijen, klantbescherming.', 'Van kracht; wordt opgevolgd door PSD3/PSR', NULL, NULL, '[{"text": "Sterke klantauthenticatie (SCA)"}, {"text": "Toegang TPP tot betaalrekeningen"}, {"text": "Klantbescherming en transparantie"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 42, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (2, 'PSD3/PSR', 'Payment Services Directive 3 & Payment Services Regulation', 'Directive+Regulation', 'EU', 'Opvolger PSD2; harmonisatie open-banking API’s; samenvoegen E-Money, versterkte consumentenbescherming en fraude-preventie.', 'In voorstel; banken bereiden API-stacks en KYC/AML-verbeteringen voor', NULL, NULL, '[{"text": "Sterkere klantbescherming"}, {"text": "Harmonisatie API-standaarden"}, {"text": "Licenties voor non-bank PSP’s"}]', '[{"text": "Toepassing verwacht vanaf eind 2025"}]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 40, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (7, 'IPR', 'Instant Payments Regulation', 'Regulation', 'EU', 'SEPA Instant beschikbaar 24/7/365; gelijke of lagere fees; realtime sancties/fraude-monitoring; naam-nummer verificatie.', 'Van kracht sinds 2024-04-08; NL banken upgraden 24/7 core, liquiditeit en realtime monitoring', NULL, NULL, '[{"text": "PSPs kunnen ontvangen per 2025-01-09"}, {"text": "PSPs kunnen verzenden en naam-check per 2025-10-09"}, {"text": "Non-euro area tot 2027-07"}]', '[{"text": "Ontvangen: 2025-01-09"}, {"text": "Verzenden + naam-check: 2025-10-09"}, {"text": "Non-euro tot 2027-07"}]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 40, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (8, 'Sanctiewet 1977 + EU', 'Sanctiewet 1977 + EU-sanctieregels', 'National law+Regulation', 'NL+EU', 'Verbod op transacties met gesanctioneerde landen, personen en entiteiten.', 'Van kracht', NULL, NULL, '[{"text": "Screening tegen sanctielijsten"}, {"text": "Blokkeren/rapporteren verboden transacties"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 42, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (9, 'OFAC', 'US Sanctions (OFAC)', 'Regulation', 'US', 'OFAC-regels gelden bij US-nexus (USD, US correspondent, US persons).', 'Van kracht; relevant bij US-exposure', NULL, NULL, '[{"text": "Screening tegen OFAC-lijsten"}, {"text": "Licenties waar vereist"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 38, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (12, 'GDPR', 'AVG / GDPR', 'Regulation', 'EU', 'Regels voor verwerking betaalgegevens en PSD2-data.', 'Van kracht', NULL, NULL, '[{"text": "Rechtsgrond"}, {"text": "Doelbinding"}, {"text": "Dataminimalisatie"}, {"text": "Rechten betrokkenen"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 41, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (14, 'eIDAS', 'eIDAS (bij authenticatie)', 'Regulation', 'EU', 'Elektronische identificatie en vertrouwensdiensten.', 'Van kracht', NULL, NULL, '[{"text": "Gekwalificeerde certificaten/diensten"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:09:05.178748+00', NULL, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (3, 'SEPA 260/2012', 'SEPA Regulation 260/2012', 'Regulation', 'EU', 'Standaardisatie eurobetalingen.', 'Van kracht', NULL, NULL, '[{"text": "IBAN/ISO-formaten en STP"}, {"text": "Harmonisatie overschrijvingen/incasso’s"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 39, 'bfsi');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (4, 'IFR', 'Interchange Fee Regulation (2015/751)', 'Regulation', 'EU', 'Limieten op interchange fees bij kaartbetalingen.', 'Van kracht sinds 2015', NULL, NULL, '[{"text": "0,2% debit"}, {"text": "0,3% credit"}, {"text": "Transparantie en concurrentie"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 40, 'grc');
INSERT INTO public.regulation (id, code, title, instrument_type, jurisdiction, scope_goals, status, effective_from, effective_to, obligations, deadlines, sources, notes, created_at, updated_at, regulator_id, domain) VALUES (5, 'Cross-Border 924/2009', 'Cross-Border Payments Regulation (Reg. 924/2009, 2019/518)', 'Regulation', 'EU', 'Gelijke kosten voor grensoverschrijdende eurobetalingen en transparantie valutakosten.', 'Van kracht', NULL, NULL, '[{"text": "Gelijke tarieven"}, {"text": "Voorafgaande bekendmaking kosten en wisselkoersopslagen"}]', '[]', '[{"text": "—"}]', '', '2025-10-03 20:51:41.633823+00', '2025-10-30 11:06:31.205668+00', 40, 'grc');


--
-- Name: bfsi_regulation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bfsi_regulation_id_seq', 18, true);


--
-- PostgreSQL database dump complete
--

\unrestrict vSmYGYObsfO0QtWw6yiKWP13C4FGfwUTsLMej3hoH2hMLAj7vO9fmz2lF4PYH24

